insert into course values (103,'Go','Arturo Vidal')
insert into course values (100,'Angular','Arturo Vidal')
insert into course values (101,'Django','Arturo Vidal')
insert into course values (102,'SASS','Arturo Vidal')
insert into course values (104,'Javascript','Arturo Vidal')
insert into course values (105,'React','Arturo Vidal')
insert into course values (106,'Java','Arturo Vidal')
insert into course values (107,'Python','Arturo Vidal')